# Generated by Django 4.0.5 on 2022-08-06 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WeGroW', '0002_remove_profile_otp_profile_city_profile_pincode_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=300)),
                ('product_quantity', models.IntegerField()),
                ('product_price', models.IntegerField()),
                ('phone_number', models.CharField(max_length=10)),
                ('country', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=20)),
                ('district', models.CharField(max_length=20)),
                ('pin_code', models.IntegerField()),
            ],
        ),
    ]
