# Generated by Django 4.0.5 on 2022-08-06 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WeGroW', '0003_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='country',
            new_name='seller_country',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='district',
            new_name='seller_district',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='state',
            new_name='seller_state',
        ),
    ]
