# Generated by Django 4.0.5 on 2022-08-13 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WeGroW', '0005_product_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact_us',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('email', models.CharField(max_length=300)),
                ('subject', models.CharField(max_length=300)),
                ('message', models.CharField(max_length=300)),
            ],
        ),
    ]
