# Generated by Django 4.0.6 on 2022-08-14 07:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WeGroW', '0007_remove_product_user_product_prodid_product_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyer_name', models.CharField(max_length=200)),
                ('buyer_phone', models.CharField(max_length=200)),
                ('prodId', models.CharField(max_length=20)),
                ('product_name', models.CharField(max_length=300)),
                ('product_quantity', models.IntegerField()),
                ('product_price', models.IntegerField()),
                ('phone_number', models.CharField(max_length=10)),
                ('seller_country', models.CharField(max_length=20)),
                ('seller_state', models.CharField(max_length=20)),
                ('seller_district', models.CharField(max_length=20)),
                ('pin_code', models.IntegerField()),
                ('profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='WeGroW.profile')),
            ],
        ),
        migrations.CreateModel(
            name='ForSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prodId', models.CharField(max_length=20)),
                ('product_name', models.CharField(max_length=300)),
                ('product_quantity', models.IntegerField()),
                ('product_price', models.IntegerField()),
                ('phone_number', models.CharField(max_length=10)),
                ('seller_country', models.CharField(max_length=20)),
                ('seller_state', models.CharField(max_length=20)),
                ('seller_district', models.CharField(max_length=20)),
                ('pin_code', models.IntegerField()),
                ('profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='WeGroW.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Bought',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seller_name', models.CharField(max_length=200)),
                ('seller_phone', models.CharField(max_length=200)),
                ('prodId', models.CharField(max_length=20)),
                ('product_name', models.CharField(max_length=300)),
                ('product_quantity', models.IntegerField()),
                ('product_price', models.IntegerField()),
                ('phone_number', models.CharField(max_length=10)),
                ('seller_country', models.CharField(max_length=20)),
                ('seller_state', models.CharField(max_length=20)),
                ('seller_district', models.CharField(max_length=20)),
                ('pin_code', models.IntegerField()),
                ('profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='WeGroW.profile')),
            ],
        ),
    ]
